:: set -x
@echo on
type nul >> %DATALAD_TESTS_SERVER_LOCALPATH%\probe
ssh -i %DATALAD_TESTS_SERVER_SSH_SECKEY% -p %DATALAD_TESTS_SERVER_SSH_PORT% %DATALAD_TESTS_SERVER_SSH_LOGIN%@%DATALAD_TESTS_SERVER_SSH_HOST% test -f %DATALAD_TESTS_SERVER_SSH_PATH%/probe
if %errorlevel% neq 0 exit /b %errorlevel%
del %DATALAD_TESTS_SERVER_LOCALPATH%\probe
